version: "3"
services:
        nginx:
                image: nginx
                container_name: nginx
                volumes:
                 - wordpress:/var/www/wordpress
                networks:
                 - inception
                depends_on:
                 - wordpress
                build:
                 context: requirements/nginx
                 dockerfile: Dockerfile
                env_file: 
                 - .env
                ports:
                 - "443:443"
                restart: on-failure

        mariadb:
                image: mariadb
                container_name: mariadb
                volumes:
                 - mariadb:/var/lib/mysql
                networks:
                 - inception
                build:
                 context: requirements/mariadb
                 dockerfile: Dockerfile
                env_file:
                 - .env
                expose: 
                 - "3306"
                restart: on-failure

        wordpress:
                image: wordpress
                container_name: wordpress
                volumes:
                 - wordpress:/var/www/wordpress
                networks:
                 - inception
                depends_on:
                 - mariadb
                build:
                 context: requirements/wordpress
                 dockerfile: Dockerfile
                env_file: 
                 - .env
                expose: 
                 - "9000"
                restart: on-failure

volumes:
        mariadb:
         driver: local
         driver_opts:
          device: '/home/trobert/data/mariadb'
          type: 'none'
          o: 'bind'

        wordpress:
         driver: local
         driver_opts:
          device: '/home/trobert/data/wordpress'
          type: 'none'
          o: 'bind'

networks:
        inception:
         driver: bridge
